### ISSUE TITLE
Problems with updating to 3.0

### ISSUE THREAD

**Issue by ziggi** [Zeex/subhook#14]
After updating subhook to 3.0 I got these errors:
```
$ make
[  6%] Built target subhook
[ 10%] Building CXX object CMakeFiles/FCNPC.dir/src/Hooks.cpp.o
In file included from /home/ziggi/devgit/FCNPC/src/Main.hpp:39:0,
                 from /home/ziggi/devgit/FCNPC/src/Hooks.cpp:11:
/home/ziggi/devgit/FCNPC/src/subhook/subhook.h: In constructor ‘SubHook::SubHook(void*, void*)’:
/home/ziggi/devgit/FCNPC/src/subhook/subhook.h:122:61: error: too few arguments to function ‘subhook* subhook_new(void*, void*, subhook_options_t)’
   SubHook(void *src, void *dst) : hook_(subhook_new(src, dst)) {}
                                                             ^
/home/ziggi/devgit/FCNPC/src/subhook/subhook.h:96:38: note: declared here
 SUBHOOK_EXPORT subhook_t SUBHOOK_API subhook_new(void *src,
                                      ^~~~~~~~~~~
/home/ziggi/devgit/FCNPC/src/subhook/subhook.h: In member function ‘bool SubHook::Install(void*, void*)’:
/home/ziggi/devgit/FCNPC/src/subhook/subhook.h:139:35: error: too few arguments to function ‘subhook* subhook_new(void*, void*, subhook_options_t)’
       hook_ = subhook_new(src, dst);
                                   ^
/home/ziggi/devgit/FCNPC/src/subhook/subhook.h:96:38: note: declared here
 SUBHOOK_EXPORT subhook_t SUBHOOK_API subhook_new(void *src,
                                      ^~~~~~~~~~~
/home/ziggi/devgit/FCNPC/src/Hooks.cpp: In static member function ‘static void CHooks::InstallHooks()’:
/home/ziggi/devgit/FCNPC/src/Hooks.cpp:325:72: error: too few arguments to function  subhook* subhook_new(void*, void*, subhook_options_t)’
  hookFindPublic = subhook_new(pFindPublic, (BYTE *)&amx_FindPublic_Hook);
                                                                        ^
In file included from /home/ziggi/devgit/FCNPC/src/Main.hpp:39:0,
                 from /home/ziggi/devgit/FCNPC/src/Hooks.cpp:11:
/home/ziggi/devgit/FCNPC/src/subhook/subhook.h:96:38: note: declared here
 SUBHOOK_EXPORT subhook_t SUBHOOK_API subhook_new(void *src,
                                      ^~~~~~~~~~~
/home/ziggi/devgit/FCNPC/src/Hooks.cpp:329:54: error: too few arguments to function  subhook* subhook_new(void*, void*, subhook_options_t)’
  hookPush = subhook_new(pPush, (BYTE *)&amx_Push_Hook);
                                                      ^
In file included from /home/ziggi/devgit/FCNPC/src/Main.hpp:39:0,
                 from /home/ziggi/devgit/FCNPC/src/Hooks.cpp:11:
/home/ziggi/devgit/FCNPC/src/subhook/subhook.h:96:38: note: declared here
 SUBHOOK_EXPORT subhook_t SUBHOOK_API subhook_new(void *src,
                                      ^~~~~~~~~~~
/home/ziggi/devgit/FCNPC/src/Hooks.cpp:333:54: error: too few arguments to function  subhook* subhook_new(void*, void*, subhook_options_t)’
  hookExec = subhook_new(pExec, (BYTE *)&amx_Exec_Hook);
                                                      ^
In file included from /home/ziggi/devgit/FCNPC/src/Main.hpp:39:0,
                 from /home/ziggi/devgit/FCNPC/src/Hooks.cpp:11:
/home/ziggi/devgit/FCNPC/src/subhook/subhook.h:96:38: note: declared here
 SUBHOOK_EXPORT subhook_t SUBHOOK_API subhook_new(void *src,
                                      ^~~~~~~~~~~
make[2]: *** [CMakeFiles/FCNPC.dir/build.make:255: CMakeFiles/FCNPC.dir/src/Hooks.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/FCNPC.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
Can you fix it please?

System information:
```
$ g++ --version
g++ (GCC) 6.1.1 20160802
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
$ uname -mosr
Linux 4.6.4-1-ARCH x86_64 GNU/Linux
```

**Comment by ziggi** [comment]
But subhook_new still have as required parameter.
```C++
SUBHOOK_EXPORT subhook_t SUBHOOK_API subhook_new(void *src,
                                                 void *dst,
                                                 subhook_options_t options);
```

**Comment by Zeex** [comment]
What do you mean? You can use `0` in case you don't want to pass any options.

**Comment by ziggi** [comment]
I can't use 0, because I got this error:
```
error C2664: 'subhook_t subhook_new(void *,void *,subhook_options_t)' : cannot convert argument 3 from 'int' to 'subhook_options_t'
2>          Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast)
```
Right syntax is:
```C++
subhook_new(..., ..., subhook_options_t(0));
```
